highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Josh Hamann's Resume
name: Josh Hamann
email: joshhamann@gmail.com
email_full: mailto:joshhamann@gmail.com
website: josh-hamann.com
website_full: http://josh-hamann.com
github: joshhamann
tel: +1 719 359 3140
tel_full: tel:+17193593140
google_maps: 'https://www.google.com/maps/place/Denver,+CO/'
place: Denver, CO
postcode: Denver
city: Colorado
country: United States
google_analytics: UA-76159685-1

# needed for travis-ci build
exclude: [vendor]
